### PR TITLE
German Regexp + Wordcount

### PR DESCRIPTION
**Pull request by NiklasHoltmeyer**
i added Regexp for the German Language and trained 
German Word Counts based on  https://dumps.wikimedia.org/dewiki/latest/ [Wikipedia Dump (07.05.2021)]
https://github.com/NiklasHoltmeyer/autocorrect/releases/tag/German

### CODE REVIEW

**Comment by fsondej** [comment]
Great, can you upload the `de.tar.gz` file somewhere? Also, please add some unit test, similar to the existing ones in `test_all.py`

**Comment by NiklasHoltmeyer** [comment]
I uploaded the de.tar.gz to https://github.com/NiklasHoltmeyer/autocorrect/releases/tag/German
https://github.com/NiklasHoltmeyer/autocorrect/releases/download/German/de.tar.gz

i will try to write some test within the next days.

**Comment by NiklasHoltmeyer** [comment]
i added tests.

**Comment by fsondej** [comment]
I see that `de.tar.gz` has 150MB which is a lot. Did you do this "find_threshold" step from https://github.com/fsondej/autocorrect#adding-new-languages to reduce dictionary size? Or is it just because of the long compound words in German so there must be a lot of words in the dictionary?

**Comment by NiklasHoltmeyer** [comment]
sorry i forghott to uploaded the clean version

https://github.com/NiklasHoltmeyer/autocorrect/releases/tag/DE-Threshhold

here is the threshhold version

**Comment by fsondej** [comment]
Hmm, in assets I only see the source code and no `de.tar.gz` like before

**Comment by NiklasHoltmeyer** [comment]
Hm Strange, i couldnt see the Files either, but they are there if i edit the Release.. I just reuploaded it and now i can see them!

https://github.com/NiklasHoltmeyer/autocorrect/releases/tag/DE-Threshhold

**Comment by fsondej** [comment]
Great, I made a new PR #34 with this dictionary url added and fixed the black errors, so I''ll close this one.

**Comment by fsondej** [comment]
also note, that this `de.tar.gz` file has bad directory structure inside and it fails, I changed it and uploaded to dropbox

**Comment by fsondej** [comment]
hmm, for some reason the tests still fail with the
```
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 337958 column 1 (char 7633222)
```

**Pull request closed without merging**
