### PR TITLE
(setup.py/constants.py/test_all.py): Add Vietnamese

### PR DESCRIPTION
**Pull request by khiemledev**
Hello @filyp, I'm interested in this work. I want to contribute my language to your repo, please tell me if there's any issue.

### CODE REVIEW

**Comment by filyp** [comment]
All looks good :)
I also need the tar.gz file you created. You can either upload it to IPFS yourself (for example with Pinata, which will pin this file so it doesn't disappear) and add the path to `ipfs_paths`, or share it with me however you like and I will upload it.

**Comment by khiemledev** [comment]
Hi @filyp, I did it!
Now you can merge the code into the main branch :)

**Comment by filyp** [comment]
The last two things:
- delete `word_count.json` from repo as it's not needed
- fix the code style with `black` (the tests are failing because of that)

**Comment by filyp** [comment]
Great, everything passes now. Vietnamese has quite low correction quality (bad: 53/64) but I assume that's because Vietnamese is just hard to autocorrect. So I'll merge.

Thanks for contributing!

**Pull request merged**
